/*Creation Code For Film Studio Database, By Abhishek Joshi*/

USE FILM_STUDIO

CREATE TABLE tblREPRESENTATIVE(
RepID INT IDENTITY(1,1) NOT NULL,
RepFName VARCHAR(60),
RepLName VARCHAR(60),
RepAddress VARCHAR(120),
RepCity VARCHAR(60),
RepState VARCHAR(60),
RepZip VARCHAR(25),
RepPhone VARCHAR(50),
RepEmail VARCHAR(60),
CONSTRAINT PK_RepID PRIMARY KEY (RepID)
)

CREATE TABLE tblVENDOR_TYPE(
VendorTypeID INT IDENTITY(1,1) NOT NULL,
VendorTypeName VARCHAR(60),
VendorTypeDescr VARCHAR(200),
CONSTRAINT PK_VendorTypeID PRIMARY KEY (VendorTypeID)
)

CREATE TABLE tblPROP_TYPE(
PropTypeID INT IDENTITY(1,1) NOT NULL,
PropTypeName VARCHAR(60),
PropTypeDescr VARCHAR(200),
CONSTRAINT PK_PropTypeID PRIMARY KEY (PropTypeID)
)

CREATE TABLE tblEQUIPMENT_TYPE(
EquipmentTypeID INT IDENTITY(1,1) NOT NULL,
EquipmentTypeName VARCHAR(60),
EquipmentTypeDescr VARCHAR(200),
CONSTRAINT PK_EquipmentTypeID PRIMARY KEY (EquipmentTypeID)
)

CREATE TABLE tblCLIENT_TYPE(
ClientTypeID INT IDENTITY(1,1) NOT NULL,
ClientTypeName VARCHAR(60),
ClientTypeDescr VARCHAR(200),
CONSTRAINT PK_ClientTypeID PRIMARY KEY (ClientTypeID)
)

CREATE TABLE tblFACILITY_TYPE(
FacilityTypeID INT IDENTITY(1,1) NOT NULL,
FacilityTypeName VARCHAR(60),
FacilityTypeDescr VARCHAR(200),
CONSTRAINT PK_FacilityTypeID PRIMARY KEY (FacilityTypeID)
)

CREATE TABLE tblDEPARTMENT(
DepartmentID INT IDENTITY(1,1) NOT NULL,
DepartmentName VARCHAR(60),
DepartmentDescr VARCHAR(200),
CONSTRAINT PK_DepartmentID PRIMARY KEY (DepartmentID)
)

CREATE TABLE tblLOCATION_TYPE(
LocationTypeID INT IDENTITY(1,1) NOT NULL,
LocationTypeName VARCHAR(60),
LocationTypeDescr VARCHAR(200),
CONSTRAINT PK_LocationTypeID PRIMARY KEY (LocationTypeID)
)

CREATE TABLE tblSTAFF(
StaffID INT IDENTITY(1,1) NOT NULL,
StaffFName VARCHAR(60),
StaffLName VARCHAR(60),
StaffAddress VARCHAR(120),
StaffCity VARCHAR(60),
StaffState VARCHAR(60),
StaffZip VARCHAR(25),
StaffPhone VARCHAR(50),
StaffEmail VARCHAR(60),
CONSTRAINT PK_StaffID PRIMARY KEY (StaffID)
)

CREATE TABLE tblVENDOR(
VendorID INT IDENTITY(1,1) NOT NULL,
VendorTypeID INT,
VendorName VARCHAR(60),
VendorAddress VARCHAR(120),
VendorCity VARCHAR(60),
VendorState VARCHAR(60),
VendorZip VARCHAR(25),
VendorPhone VARCHAR(50),
VendorEmail VARCHAR(60),
CONSTRAINT PK_VendorID PRIMARY KEY (VendorID),
CONSTRAINT FK_VendorTypeID FOREIGN KEY (VendorTypeID)
REFERENCES tblVENDOR_TYPE(VendorTypeID)
)

CREATE TABLE tblCLIENT(
ClientID INT IDENTITY(1,1) NOT NULL,
ClientTypeID INT,
ClientName VARCHAR(60),
ClientAddress VARCHAR(120),
ClientCity VARCHAR(60),
ClientState VARCHAR(60),
ClientZip VARCHAR(25),
ClientPhone VARCHAR(50),
ClientEmail VARCHAR(60),
CONSTRAINT PK_ClientID PRIMARY KEY (ClientID),
CONSTRAINT FK_ClientTypeID FOREIGN KEY (ClientTypeID)
REFERENCES tblCLIENT_TYPE(ClientTypeID)
)

CREATE TABLE tblFACILITY(
FacilityID INT IDENTITY(1,1) NOT NULL,
FacilityTypeID INT,
FacilityName VARCHAR(60),
FacilityAddress VARCHAR(120),
FacilityCity VARCHAR(60),
FacilityState VARCHAR(60),
FacilityZip VARCHAR(25),
FacilityPhone VARCHAR(50),
FacilityEmail VARCHAR(60),
CONSTRAINT PK_FacilityID PRIMARY KEY (FacilityID),
CONSTRAINT FK_FacilityTypeID FOREIGN KEY (FacilityTypeID)
REFERENCES tblFACILITY_TYPE(FacilityTypeID)
)

CREATE TABLE tblSHOOTING_LOCATION(
LocationID INT IDENTITY(1,1) NOT NULL,
LocationTypeID INT,
LocationName VARCHAR(60),
LocationAddress VARCHAR(120),
LocationCity VARCHAR(60),
LocationState VARCHAR(60),
LocationZip VARCHAR(25),
LocationDescr VARCHAR(200),
CONSTRAINT PK_LocationID PRIMARY KEY (LocationID),
CONSTRAINT FK_LocationTypeID FOREIGN KEY (LocationTypeID)
REFERENCES tblLOCATION_TYPE(LocationTypeID)
)

CREATE TABLE tblEQUIPMENT(
EquipmentID INT IDENTITY(1,1) NOT NULL,
EquipmentTypeID INT,
EquipmentName VARCHAR(60),
EquipmentDescr VARCHAR(200),
CONSTRAINT PK_EquipmentID PRIMARY KEY (EquipmentID),
CONSTRAINT FK_EquipmentTypeID FOREIGN KEY (EquipmentTypeID)
REFERENCES tblEQUIPMENT_TYPE(EquipmentTypeID)
)

CREATE TABLE tblPROP(
PropID INT IDENTITY(1,1) NOT NULL,
PropTypeID INT,
PropName VARCHAR(60),
PropDescr VARCHAR(200),
CONSTRAINT PK_PropID PRIMARY KEY (PropID),
CONSTRAINT FK_PropTypeID FOREIGN KEY (PropTypeID)
REFERENCES tblPROP_TYPE(PropTypeID)
)

CREATE TABLE tblPOSITION(
PositionID INT IDENTITY(1,1) NOT NULL,
DepartmentID INT NOT NULL,
PositionName VARCHAR(60),
PositionDescr VARCHAR(200),
CONSTRAINT PK_PositionID PRIMARY KEY (PositionID),
CONSTRAINT FK_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES tblDEPARTMENT(DepartmentID)
)

CREATE TABLE tblCONTRACT(
ContractID INT IDENTITY(1,1) NOT NULL,
ClientID INT NOT NULL,
ContractName VARCHAR(60),
ContractDescr VARCHAR(200),
BeginDatePlanned DATE,
EndDatePlanned DATE,
BeginDateActual DATE,
EndDateActual DATE,
CONSTRAINT PK_ContractID PRIMARY KEY (ContractID),
CONSTRAINT FK_ClientID FOREIGN KEY (ClientID)
REFERENCES tblCLIENT(ClientID)
)

CREATE TABLE tblPROJECT(
ProjectID INT IDENTITY(1,1) NOT NULL,
ContractID INT NOT NULL,
ProjectName VARCHAR(60),
ProjectDescr VARCHAR(200),
BeginDatePlanned DATE,
EndDatePlanned DATE,
BeginDateActual DATE,
EndDateActual DATE,
CONSTRAINT PK_ProjectID PRIMARY KEY (ProjectID),
CONSTRAINT FK_ContractID FOREIGN KEY (ContractID)
REFERENCES tblContract(ContractID)
)

CREATE TABLE tblSTAFF_POSITION(
StaffID INT NOT NULL,
PositionID INT NOT NULL,
CONSTRAINT PK_Staff_Position PRIMARY KEY (StaffID, PositionID),
CONSTRAINT FK_StaffID FOREIGN KEY (StaffID)
REFERENCES tblSTAFF(StaffID),
CONSTRAINT FK_PositionID FOREIGN KEY (PositionID)
REFERENCES tblPOSITION(PositionID)
)

CREATE TABLE tblPROJECT_FACILITY(
ProjectID INT NOT NULL,
FacilityID INT NOT NULL,
CONSTRAINT PK_Project_Facility PRIMARY KEY (ProjectID, FacilityID),
CONSTRAINT FK_ProjectID FOREIGN KEY (ProjectID)
REFERENCES tblPROJECT(ProjectID),
CONSTRAINT FK_FacilityID FOREIGN KEY (FacilityID)
REFERENCES tblFACILITY(FacilityID)
)

CREATE TABLE tblSTAFF_PROJECT(
ProjectID INT NOT NULL,
StaffID INT NOT NULL,
CONSTRAINT PK_Staff_Project PRIMARY KEY (ProjectID, StaffID),
CONSTRAINT FK_Staff_ProjectID FOREIGN KEY (ProjectID)
REFERENCES tblPROJECT(ProjectID),
CONSTRAINT FK_Project_StaffID FOREIGN KEY (StaffID)
REFERENCES tblSTAFF(StaffID)
)

CREATE TABLE tblPROJECT_LOCATION(
ProjectID INT NOT NULL,
LocationID INT NOT NULL,
CONSTRAINT PK_Project_Location PRIMARY KEY (ProjectID, LocationID),
CONSTRAINT FK_Location_ProjectID FOREIGN KEY (ProjectID)
REFERENCES tblPROJECT(ProjectID),
CONSTRAINT FK_Project_LocationID FOREIGN KEY (LocationID)
REFERENCES tblSHOOTING_LOCATION(LocationID)
)

CREATE TABLE tblPROJECT_EQUIPMENT(
ProjectID INT NOT NULL,
EquipmentID INT NOT NULL,
Qty INT,
CONSTRAINT PK_Project_Equipment PRIMARY KEY (ProjectID, EquipmentID),
CONSTRAINT FK_Equipment_ProjectID FOREIGN KEY (ProjectID)
REFERENCES tblPROJECT(ProjectID),
CONSTRAINT FK_Project_EquipmentID FOREIGN KEY (EquipmentID)
REFERENCES tblEQUIPMENT(EquipmentID)
)

CREATE TABLE tblPROJECT_PROP(
ProjectID INT NOT NULL,
PropID INT NOT NULL,
Qty INT,
CONSTRAINT PK_Project_Prop PRIMARY KEY (ProjectID, PropID),
CONSTRAINT FK_Prop_ProjectID FOREIGN KEY (ProjectID)
REFERENCES tblPROJECT(ProjectID),
CONSTRAINT FK_Project_PropID FOREIGN KEY (PropID)
REFERENCES tblPROP(PropID)
)

CREATE TABLE tblCLIENT_REP(
ClientID INT NOT NULL,
RepID INT NOT NULL,
CONSTRAINT PK_Client_Rep PRIMARY KEY (ClientID, RepID),
CONSTRAINT FK_Rep_ClientID FOREIGN KEY (RepID)
REFERENCES tblREPRESENTATIVE(RepID),
CONSTRAINT FK_Client_RepID FOREIGN KEY (ClientID)
REFERENCES tblCLIENT(ClientID)
)

CREATE TABLE tblLOCATION_REP(
LocationID INT NOT NULL,
RepID INT NOT NULL,
CONSTRAINT PK_Location_Rep PRIMARY KEY (LocationID, RepID),
CONSTRAINT FK_Rep_LocationID FOREIGN KEY (RepID)
REFERENCES tblREPRESENTATIVE(RepID),
CONSTRAINT FK_Location_RepID FOREIGN KEY (LocationID)
REFERENCES tblSHOOTING_LOCATION(LocationID)
)

CREATE TABLE tblVENDOR_REP(
VendorID INT NOT NULL,
RepID INT NOT NULL,
CONSTRAINT PK_Vendor_Rep PRIMARY KEY (VendorID, RepID),
CONSTRAINT FK_Rep_VendorID FOREIGN KEY (RepID)
REFERENCES tblREPRESENTATIVE(RepID),
CONSTRAINT FK_Vendor_RepID FOREIGN KEY (VendorID)
REFERENCES tblVENDOR(VendorID)
)

CREATE TABLE tblSTAFF_EQUIPMENT(
StaffID INT NOT NULL,
EquipmentID INT NOT NULL,
CheckOutDate DATETIME NOT NULL,
ReturnDate DATETIME,
CONSTRAINT PK_Staff_Equipment PRIMARY KEY (EquipmentID, StaffID),
CONSTRAINT FK_Staff_EquipmentID FOREIGN KEY (StaffID)
REFERENCES tblSTAFF(StaffID),
CONSTRAINT FK_Equipment_StaffID FOREIGN KEY (EquipmentID)
REFERENCES tblEQUIPMENT(EquipmentID)
)

CREATE TABLE tblSTAFF_PROP(
StaffID INT NOT NULL,
PropID INT NOT NULL,
CheckOutDate DATETIME NOT NULL,
ReturnDate DATETIME,
CONSTRAINT PK_Staff_Prop PRIMARY KEY (PropID, StaffID),
CONSTRAINT FK_Staff_PropID FOREIGN KEY (StaffID)
REFERENCES tblSTAFF(StaffID),
CONSTRAINT FK_Prop_StaffID FOREIGN KEY (PropID)
REFERENCES tblPROP(PropID)
)

CREATE TABLE tblEQUIPMENT_VENDOR(
EquipmentID INT NOT NULL,
VendorID INT NOT NULL,
Price INT NOT NULL,
StockOnHand INT NOT NULL,
CONSTRAINT PK_Equipment_Vendor PRIMARY KEY (VendorID, EquipmentID),
CONSTRAINT FK_Equipment_VendorID FOREIGN KEY (EquipmentID)
REFERENCES tblEQUIPMENT(EquipmentID),
CONSTRAINT FK_Vendor_EquipmentID FOREIGN KEY (VendorID)
REFERENCES tblVENDOR(VendorID)
)

CREATE TABLE tblPROP_VENDOR(
PropID INT NOT NULL,
VendorID INT NOT NULL,
Price INT NOT NULL,
StockOnHand INT NOT NULL,
CONSTRAINT PK_Prop_Vendor PRIMARY KEY (VendorID, PropID),
CONSTRAINT FK_Prop_VendorID FOREIGN KEY (PropID)
REFERENCES tblPROP(PropID),
CONSTRAINT FK_Vendor_PropID FOREIGN KEY (VendorID)
REFERENCES tblVENDOR(VendorID)
)
